### ISSUE TITLE
users shouldn't be able to invite members to a group that are already members of that group

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/invite-anyone#2]

**Comment by modelm** [comment]
I tested this and it doesn't seem to be an issue anymore.

I created two groups, invited a user to one of them, and that user only shows up on the invite autocomplete of the group they're not a member of.

User tnwilliams is in the list of autocompleted users because they are not already a member:
<img width="461" alt="screen shot 2015-10-14 at 11 23 43 am" src="https://cloud.githubusercontent.com/assets/330857/10488405/837afa2e-7266-11e5-9298-28d263ded886.png">

Member tnwilliams is not in the list of autocompleted users:
<img width="412" alt="screen shot 2015-10-14 at 11 23 51 am" src="https://cloud.githubusercontent.com/assets/330857/10488407/85c0194a-7266-11e5-9e57-2241a4cfedfd.png">

**Comment by modelm** [comment]
duplicate upstream issue: https://github.com/boonebgorges/invite-anyone/issues/29
